//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhDuHoc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMT
    {
        public string SoCMT { get; set; }
        public string HoTen { get; set; }
        public string TenGoiKhac { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string QuocTich { get; set; }
        public string QueQuan { get; set; }
        public string NoiThuongTru { get; set; }
        public Nullable<System.DateTime> GiaTriDen { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string DauVetRieng { get; set; }
        public System.DateTime NgayCap { get; set; }
        public string NoiCap { get; set; }
        public int LoaiCMT { get; set; }
        public string fileCMT { get; set; }
    }
}
