//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhDuHoc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAYKHAISINH
    {
        public int id { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string QueQuan { get; set; }
        public string GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string QuocTich { get; set; }
        public string HoTenMe { get; set; }
        public string NsMe { get; set; }
        public string DanTocMe { get; set; }
        public string QuocTichMe { get; set; }
        public string NoiCuTruMe { get; set; }
        public string HoTenBo { get; set; }
        public string NsBo { get; set; }
        public string DanTocBo { get; set; }
        public string QuocTichBo { get; set; }
        public string NoiCuTruBo { get; set; }
        public string NoiDangKy { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string fileGKS { get; set; }
    }
}
