//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhDuHoc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiayNhapHoc
    {
        public int id_gnh { get; set; }
        public string Ten { get; set; }
        public string TinhTrangHn { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> HoChieu { get; set; }
        public Nullable<int> NamHc { get; set; }
        public Nullable<int> ThangHc { get; set; }
        public Nullable<int> NgayHc { get; set; }
        public string NoiOHienTai { get; set; }
        public string TruongC1 { get; set; }
        public string DiaChiC1 { get; set; }
        public string Ngaybd1 { get; set; }
        public string Ngaykt1 { get; set; }
        public Nullable<int> Tong1 { get; set; }
        public string TruongC2 { get; set; }
        public string DiaChiC2 { get; set; }
        public string Ngaybd2 { get; set; }
        public string Ngaykt2 { get; set; }
        public Nullable<int> Tong2 { get; set; }
        public string TruongC3 { get; set; }
        public string DiaChiC3 { get; set; }
        public string Ngaybd3 { get; set; }
        public string Ngaykt3 { get; set; }
        public Nullable<int> Tong3 { get; set; }
        public string TenTrungTam1 { get; set; }
        public string DiaChitt1 { get; set; }
        public string NgayNhapHoc1 { get; set; }
        public string NgayThoiHoc1 { get; set; }
        public string TenTrungTam2 { get; set; }
        public string DiaChitt2 { get; set; }
        public string NgayNhapHoc2 { get; set; }
        public string NgayThoiHoc2 { get; set; }
        public string TenTrungTam3 { get; set; }
        public string Diachitt3 { get; set; }
        public string NgayNhapHoc3 { get; set; }
        public string NgayThoiHoc3 { get; set; }
        public string TenCty { get; set; }
        public string DiaChiCty { get; set; }
        public string NgayVaoCty { get; set; }
        public string NgayRaCty { get; set; }
        public string NgayNhapCanh { get; set; }
        public string NgayKhoiHanh { get; set; }
        public string TinhTrang { get; set; }
        public string MucDichNhapCanh { get; set; }
        public string MucDichDuHoc { get; set; }
        public string KeHoachSauHoc { get; set; }
        public string ThoiLuongHoc { get; set; }
        public string TinhTrangBiTuChoi { get; set; }
        public string TinhTrangXinVisa { get; set; }
        public string ViPham { get; set; }
        public Nullable<int> NgayLap { get; set; }
        public Nullable<int> ThangLap { get; set; }
        public Nullable<int> NamLap { get; set; }
        public string NguoiLap { get; set; }
        public Nullable<int> id_hs { get; set; }
    }
}
