//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhDuHoc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCBA
    {
        public int id { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string NoiSongHienTai { get; set; }
        public string HoTenBo { get; set; }
        public string NgheNghiepBo { get; set; }
        public string HoTenMe { get; set; }
        public string NgheNghiepMe { get; set; }
        public string NguoiGiamHo { get; set; }
        public string NgheNghiepNGH { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string fileHB { get; set; }
    }
}
