//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhDuHoc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoKhau
    {
        public int id_hokhau { get; set; }
        public string HoTen { get; set; }
        public string QuocTich { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string DiaChi { get; set; }
        public string NgheNghiep { get; set; }
        public string QuanHe { get; set; }
        public Nullable<int> id_hs { get; set; }
    }
}
