//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhDuHoc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIHOC
    {
        public int id { get; set; }
        public string TenKiHoc { get; set; }
        public Nullable<int> id_NAMHOC { get; set; }
        public Nullable<double> Toan { get; set; }
        public Nullable<double> Ly { get; set; }
        public Nullable<double> Hoa { get; set; }
        public Nullable<double> Sinh { get; set; }
        public Nullable<double> Tin { get; set; }
        public Nullable<double> Van { get; set; }
        public Nullable<double> Su { get; set; }
        public Nullable<double> Dia { get; set; }
        public Nullable<double> NgoaiNgu { get; set; }
        public Nullable<double> CongNghe { get; set; }
        public Nullable<double> QuocPhongAnNinh { get; set; }
        public string TheDuc { get; set; }
        public Nullable<double> TuChon { get; set; }
        public Nullable<double> GiaoDucCongDan { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
    }
}
